const { pool } = require('../models/database');

const createSkillsTable = async () => {
  try {
    console.log('Creating skills table...');

    // Create skills table
    await pool.query(`
      CREATE TABLE IF NOT EXISTS skills (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL UNIQUE,
        description TEXT NOT NULL,
        damage_dice VARCHAR(20),
        damage_type VARCHAR(50),
        range_size VARCHAR(100),
        usage_frequency VARCHAR(100),
        level_requirement INTEGER DEFAULT 1,
        class_restriction VARCHAR(50),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `);

    console.log('Skills table created successfully');

    // Define all skills first (we'll use this for both seeding and updating)
    const defaultSkills = [
      // Barbarian Skills
      { name: 'Rage', description: 'Enter a furious rage for 1 minute, gaining advantage on Strength checks and saves, bonus damage on melee attacks, and resistance to physical damage.', damage_dice: '+2', damage_type: 'Bonus', range_size: 'Self', usage_frequency: '2 per long rest (increases with level)', level_requirement: 1, class_restriction: 'Barbarian' },
      { name: 'Unarmored Defense (Barbarian)', description: 'While not wearing armor, your AC equals 10 + your Dexterity modifier + your Constitution modifier. You can use a shield and still gain this benefit.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 1, class_restriction: 'Barbarian' },
      { name: 'Reckless Attack', description: 'Throw aside all concern for defense to attack with fierce desperation. Gain advantage on melee weapon attack rolls using Strength during this turn, but attack rolls against you have advantage until your next turn.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'At will', level_requirement: 2, class_restriction: 'Barbarian' },
      { name: 'Danger Sense', description: 'You have advantage on Dexterity saving throws against effects that you can see, such as traps and spells. To gain this benefit, you can\'t be blinded, deafened, or incapacitated.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 2, class_restriction: 'Barbarian' },
      { name: 'Fast Movement', description: 'Your speed increases by 10 feet while you aren\'t wearing heavy armor.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 5, class_restriction: 'Barbarian' },
      { name: 'Feral Instinct', description: 'Your instincts are so honed that you have advantage on initiative rolls. Additionally, if you are surprised at the beginning of combat and aren\'t incapacitated, you can act normally on your first turn, but only if you enter your rage before doing anything else on that turn.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 7, class_restriction: 'Barbarian' },
      { name: 'Brutal Critical', description: 'You can roll one additional weapon damage die when determining the extra damage for a critical hit with a melee attack. This increases to two additional dice at 13th level and three additional dice at 17th level.', damage_dice: '+1 die', damage_type: 'Weapon', range_size: 'Melee', usage_frequency: 'On critical hits', level_requirement: 9, class_restriction: 'Barbarian' },
      { name: 'Relentless Rage', description: 'Your rage can keep you fighting despite grievous wounds. If you drop to 0 hit points while raging and don\'t die outright, you can make a DC 10 Constitution saving throw. If you succeed, you drop to 1 hit point instead. The DC increases by 5 for each use after the first, resetting after a short or long rest.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'When reduced to 0 HP', level_requirement: 11, class_restriction: 'Barbarian' },
      { name: 'Persistent Rage', description: 'Your rage is so fierce that it ends early only if you fall unconscious or if you choose to end it.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 15, class_restriction: 'Barbarian' },
      { name: 'Indomitable Might', description: 'If your total for a Strength check is less than your Strength score, you can use your Strength score in place of the total.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 18, class_restriction: 'Barbarian' },
      { name: 'Primal Champion', description: 'Your Strength and Constitution scores increase by 4. Your maximum for those scores is now 24.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 20, class_restriction: 'Barbarian' },
      
      // Bard Skills
      { name: 'Bardic Inspiration', description: 'You can inspire others through stirring words or music. Use a bonus action to choose one creature within 60 feet who can hear you. That creature gains one Bardic Inspiration die (d6), which they can add to one ability check, attack roll, or saving throw within the next 10 minutes.', damage_dice: 'd6-d12', damage_type: 'Support', range_size: '60 feet', usage_frequency: 'Charisma modifier per long rest', level_requirement: 1, class_restriction: 'Bard' },
      { name: 'Jack of All Trades', description: 'You can add half your proficiency bonus, rounded down, to any ability check you make that doesn\'t already include your proficiency bonus.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 2, class_restriction: 'Bard' },
      { name: 'Song of Rest', description: 'You can use soothing music or oration to help revitalize your wounded allies during a short rest. Any ally who hears your song regains extra hit points at the end of the short rest.', damage_dice: 'd6-d12', damage_type: 'Healing', range_size: '30 feet', usage_frequency: 'Per short rest', level_requirement: 2, class_restriction: 'Bard' },
      { name: 'Expertise', description: 'Choose two of your skill proficiencies. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies. At 10th level, you choose two more skills.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 3, class_restriction: 'Bard' },
      { name: 'Font of Inspiration', description: 'You regain all of your expended uses of Bardic Inspiration when you finish a short or long rest.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 5, class_restriction: 'Bard' },
      { name: 'Countercharm', description: 'You can use musical notes or words of power to disrupt mind-influencing effects. As an action, you can start a performance that lasts until the end of your next turn. Allies within 30 feet who can hear you have advantage on saving throws against being frightened or charmed.', damage_dice: null, damage_type: null, range_size: '30 feet', usage_frequency: 'At will', level_requirement: 6, class_restriction: 'Bard' },
      { name: 'Magical Secrets', description: 'You learn two spells of your choice from any class. The spells must be of a level you can cast. You learn two additional spells at 14th level and two more at 18th level.', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: 'Spellcasting', level_requirement: 10, class_restriction: 'Bard' },
      { name: 'Superior Inspiration', description: 'When you roll initiative and have no uses of Bardic Inspiration left, you regain one use.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Per initiative', level_requirement: 20, class_restriction: 'Bard' },
      
      // Cleric Skills
      { name: 'Channel Divinity', description: 'You can channel divine energy directly from your deity, using that energy to fuel magical effects. You start with two such effects: Turn Undead and an effect determined by your domain. Some domains grant additional effects as you advance in levels.', damage_dice: 'Varies', damage_type: 'Divine', range_size: '30 feet', usage_frequency: '1 per rest (increases with level)', level_requirement: 2, class_restriction: 'Cleric' },
      { name: 'Turn Undead', description: 'As an action, present your holy symbol and speak a prayer censuring the undead. Each undead that can see or hear you within 30 feet must make a Wisdom saving throw. If the creature fails, it is turned for 1 minute or until it takes damage.', damage_dice: null, damage_type: 'Control', range_size: '30 feet', usage_frequency: 'Channel Divinity', level_requirement: 2, class_restriction: 'Cleric' },
      { name: 'Destroy Undead', description: 'When an undead fails its saving throw against your Turn Undead feature, the creature is instantly destroyed if its challenge rating is at or below a certain threshold (starting at 1/2 at 5th level, increasing with levels).', damage_dice: 'Instant Kill', damage_type: 'Divine', range_size: '30 feet', usage_frequency: 'With Turn Undead', level_requirement: 5, class_restriction: 'Cleric' },
      { name: 'Divine Intervention', description: 'You can call on your deity to intervene on your behalf. Describe the assistance you seek and roll d%. If you roll equal to or lower than your cleric level, your deity intervenes. Otherwise, you can\'t use this feature again for 7 days. If successful, you can\'t use it again for 7 days. At 20th level, it automatically succeeds.', damage_dice: null, damage_type: 'Divine', range_size: 'Unlimited', usage_frequency: '1 attempt per 7 days', level_requirement: 10, class_restriction: 'Cleric' },
      
      // Druid Skills
      { name: 'Druidic', description: 'You know Druidic, the secret language of druids. You can speak the language and use it to leave hidden messages. You and others who know this language automatically spot such a message. Others spot the message\'s presence with a successful DC 15 Wisdom (Perception) check but can\'t decipher it without magic.', damage_dice: null, damage_type: null, range_size: 'Special', usage_frequency: 'Passive', level_requirement: 1, class_restriction: 'Druid' },
      { name: 'Wild Shape', description: 'You can use your action to magically assume the shape of a beast that you have seen before. You can stay in beast shape for a number of hours equal to half your druid level (rounded down). You can use this feature twice per short rest.', damage_dice: 'Varies', damage_type: 'Transformation', range_size: 'Self', usage_frequency: '2 per short rest', level_requirement: 2, class_restriction: 'Druid' },
      { name: 'Timeless Body (Druid)', description: 'The primal magic that you wield causes you to age more slowly. For every 10 years that pass, your body ages only 1 year.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 18, class_restriction: 'Druid' },
      { name: 'Beast Spells', description: 'You can cast many of your druid spells in any shape you assume using Wild Shape. You can perform the somatic and verbal components of a druid spell while in a beast shape.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'While Wild Shaped', level_requirement: 18, class_restriction: 'Druid' },
      { name: 'Archdruid', description: 'You can use your Wild Shape an unlimited number of times. Additionally, you can ignore the verbal and somatic components of your druid spells, as well as any material components that lack a cost and aren\'t consumed by a spell.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 20, class_restriction: 'Druid' },
      
      // Fighter Skills
      { name: 'Fighting Style', description: 'You adopt a particular style of fighting as your specialty. Choose one fighting style option such as Archery, Defense, Dueling, Great Weapon Fighting, Protection, or Two-Weapon Fighting. Each provides unique combat benefits.', damage_dice: 'Varies', damage_type: null, range_size: 'Varies', usage_frequency: 'Passive', level_requirement: 1, class_restriction: 'Fighter, Paladin, Ranger' },
      { name: 'Second Wind', description: 'You have a limited well of stamina that you can draw on to protect yourself from harm. On your turn, you can use a bonus action to regain hit points equal to 1d10 + your fighter level.', damage_dice: '1d10 + level', damage_type: 'Healing', range_size: 'Self', usage_frequency: '1 per short rest', level_requirement: 1, class_restriction: 'Fighter' },
      { name: 'Action Surge', description: 'You can push yourself beyond your normal limits for a moment. On your turn, you can take one additional action. You can use this feature twice between rests starting at 17th level.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: '1 per short rest', level_requirement: 2, class_restriction: 'Fighter' },
      { name: 'Extra Attack', description: 'You can attack twice, instead of once, whenever you take the Attack action on your turn. The number of attacks increases to three when you reach 11th level and to four when you reach 20th level.', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: 'Passive', level_requirement: 5, class_restriction: 'Fighter' },
      { name: 'Indomitable', description: 'You can reroll a saving throw that you fail. If you do so, you must use the new roll. You can use this feature twice between long rests starting at 13th level and three times between long rests starting at 17th level.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: '1 per long rest', level_requirement: 9, class_restriction: 'Fighter' },
      
      // Monk Skills
      { name: 'Martial Arts', description: 'You gain the following benefits while you are unarmed or wielding only monk weapons: You can use Dexterity instead of Strength for attack and damage rolls. You can roll a d4 in place of the normal damage of your unarmed strike or monk weapon (this die increases with levels). When you use the Attack action with an unarmed strike or monk weapon on your turn, you can make one unarmed strike as a bonus action.', damage_dice: '1d4 to 1d10', damage_type: 'Bludgeoning', range_size: 'Melee', usage_frequency: 'Passive', level_requirement: 1, class_restriction: 'Monk' },
      { name: 'Unarmored Defense (Monk)', description: 'While you are wearing no armor and not wielding a shield, your AC equals 10 + your Dexterity modifier + your Wisdom modifier.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 1, class_restriction: 'Monk' },
      { name: 'Ki', description: 'Your training allows you to harness the mystic energy of ki. You have ki points equal to your monk level, which you can spend to fuel various ki features. You regain all expended ki points when you finish a short or long rest.', damage_dice: null, damage_type: 'Ki', range_size: 'Self', usage_frequency: 'Per short rest', level_requirement: 2, class_restriction: 'Monk' },
      { name: 'Flurry of Blows', description: 'Immediately after you take the Attack action on your turn, you can spend 1 ki point to make two unarmed strikes as a bonus action.', damage_dice: '2 unarmed strikes', damage_type: 'Bludgeoning', range_size: 'Melee', usage_frequency: '1 ki point', level_requirement: 2, class_restriction: 'Monk' },
      { name: 'Patient Defense', description: 'You can spend 1 ki point to take the Dodge action as a bonus action on your turn.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: '1 ki point', level_requirement: 2, class_restriction: 'Monk' },
      { name: 'Step of the Wind', description: 'You can spend 1 ki point to take the Disengage or Dash action as a bonus action on your turn, and your jump distance is doubled for the turn.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: '1 ki point', level_requirement: 2, class_restriction: 'Monk' },
      { name: 'Deflect Missiles', description: 'You can use your reaction to deflect or catch a missile when hit by a ranged weapon attack. The damage you take is reduced by 1d10 + your Dexterity modifier + your monk level. If you reduce the damage to 0, you can catch the missile if it\'s small enough to hold in one hand. If you catch it, you can spend 1 ki point to make a ranged attack with it as part of the same reaction.', damage_dice: '1d10 + Dex + Level', damage_type: 'Damage Reduction', range_size: 'Self', usage_frequency: 'Reaction', level_requirement: 3, class_restriction: 'Monk' },
      { name: 'Slow Fall', description: 'You can use your reaction when you fall to reduce any falling damage you take by an amount equal to five times your monk level.', damage_dice: null, damage_type: 'Damage Reduction', range_size: 'Self', usage_frequency: 'Reaction', level_requirement: 4, class_restriction: 'Monk' },
      { name: 'Stunning Strike', description: 'You can interfere with the flow of ki in an opponent\'s body. When you hit another creature with a melee weapon attack, you can spend 1 ki point to attempt a stunning strike. The target must succeed on a Constitution saving throw or be stunned until the end of your next turn.', damage_dice: null, damage_type: 'Control', range_size: 'Melee', usage_frequency: '1 ki point per use', level_requirement: 5, class_restriction: 'Monk' },
      { name: 'Ki-Empowered Strikes', description: 'Your unarmed strikes count as magical for the purpose of overcoming resistance and immunity to nonmagical attacks and damage.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 6, class_restriction: 'Monk' },
      { name: 'Evasion (Monk)', description: 'When you are subjected to an effect that allows you to make a Dexterity saving throw to take only half damage, you instead take no damage if you succeed on the saving throw, and only half damage if you fail.', damage_dice: null, damage_type: 'Defense', range_size: 'Self', usage_frequency: 'Passive', level_requirement: 7, class_restriction: 'Monk' },
      { name: 'Stillness of Mind', description: 'You can use your action to end one effect on yourself that is causing you to be charmed or frightened.', damage_dice: null, damage_type: 'Control Immunity', range_size: 'Self', usage_frequency: 'Action', level_requirement: 7, class_restriction: 'Monk' },
      { name: 'Purity of Body', description: 'You are immune to disease and poison.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 10, class_restriction: 'Monk' },
      { name: 'Tongue of the Sun and Moon', description: 'You learn to touch the ki of other minds so that you understand all spoken languages. Moreover, any creature that can understand a language can understand what you say.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 13, class_restriction: 'Monk' },
      { name: 'Diamond Soul', description: 'You gain proficiency in all saving throws. Additionally, whenever you make a saving throw and fail, you can spend 1 ki point to reroll it and take the second result.', damage_dice: null, damage_type: 'Defense', range_size: 'Self', usage_frequency: 'Passive/1 ki point', level_requirement: 14, class_restriction: 'Monk' },
      { name: 'Timeless Body (Monk)', description: 'Your ki sustains you so that you suffer none of the frailty of old age, and you can\'t be aged magically. You can still die of old age, however. Additionally, you no longer need food or water.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 15, class_restriction: 'Monk' },
      { name: 'Empty Body', description: 'You can spend 4 ki points to become invisible for 1 minute. During that time, you also have resistance to all damage but force damage. Additionally, you can spend 8 ki points to cast the astral projection spell without needing material components.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: '4-8 ki points', level_requirement: 18, class_restriction: 'Monk' },
      { name: 'Perfect Self', description: 'When you roll for initiative and have no ki points remaining, you regain 4 ki points.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'When initiative is rolled', level_requirement: 20, class_restriction: 'Monk' },
      
      // Paladin Skills
      { name: 'Divine Sense', description: 'You can detect good and evil. As an action, you know the location of any celestial, fiend, or undead within 60 feet of you that is not behind total cover. You know the type of any being whose presence you sense. You can use this feature a number of times equal to 1 + your Charisma modifier.', damage_dice: null, damage_type: 'Detection', range_size: '60 feet', usage_frequency: '1 + CHA mod per long rest', level_requirement: 1, class_restriction: 'Paladin' },
      { name: 'Lay on Hands', description: 'Your blessed touch can heal wounds. You have a pool of healing power equal to your paladin level × 5. As an action, you can touch a creature and restore hit points from that pool (max equal to the pool). You can also spend 5 points to cure one disease or neutralize one poison.', damage_dice: 'Level × 5', damage_type: 'Healing', range_size: 'Touch', usage_frequency: 'Pool per long rest', level_requirement: 1, class_restriction: 'Paladin' },
      { name: 'Divine Smite', description: 'When you hit a creature with a melee weapon attack, you can expend one spell slot to deal radiant damage to the target, in addition to the weapon\'s damage. The extra damage is 2d8 for a 1st-level spell slot, plus 1d8 for each spell level higher than 1st, to a maximum of 5d8. The damage increases by 1d8 if the target is an undead or fiend.', damage_dice: '2d8-6d8', damage_type: 'Radiant', range_size: 'Melee', usage_frequency: 'Per spell slot', level_requirement: 2, class_restriction: 'Paladin' },
      { name: 'Divine Health', description: 'The divine magic flowing through you makes you immune to disease.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 3, class_restriction: 'Paladin' },
      { name: 'Aura of Protection', description: 'Whenever you or a friendly creature within 10 feet of you must make a saving throw, the creature gains a bonus to the saving throw equal to your Charisma modifier (minimum of +1). At 18th level, the range increases to 30 feet.', damage_dice: null, damage_type: 'Support', range_size: '10-30 feet', usage_frequency: 'Passive', level_requirement: 6, class_restriction: 'Paladin' },
      { name: 'Aura of Courage', description: 'You and friendly creatures within 10 feet of you can\'t be frightened while you are conscious. At 18th level, the range increases to 30 feet.', damage_dice: null, damage_type: 'Support', range_size: '10-30 feet', usage_frequency: 'Passive', level_requirement: 10, class_restriction: 'Paladin' },
      { name: 'Improved Divine Smite', description: 'You are so suffused with righteous might that all your melee weapon strikes carry divine power with them. Whenever you hit a creature with a melee weapon, the creature takes an extra 1d8 radiant damage.', damage_dice: '1d8', damage_type: 'Radiant', range_size: 'Melee', usage_frequency: 'Passive', level_requirement: 11, class_restriction: 'Paladin' },
      { name: 'Cleansing Touch', description: 'You can use your action to end one spell on yourself or on one willing creature that you touch. You can use this feature a number of times equal to your Charisma modifier (minimum of once). You regain expended uses when you finish a long rest.', damage_dice: null, damage_type: 'Support', range_size: 'Touch', usage_frequency: 'CHA mod per long rest', level_requirement: 14, class_restriction: 'Paladin' },
      
      // Ranger Skills
      { name: 'Favored Enemy', description: 'You have significant experience studying, tracking, hunting, and even talking to a certain type of enemy. Choose a type of favored enemy. You have advantage on Wisdom (Survival) checks to track your favored enemies and on Intelligence checks to recall information about them.', damage_dice: null, damage_type: null, range_size: 'Special', usage_frequency: 'Passive', level_requirement: 1, class_restriction: 'Ranger' },
      { name: 'Natural Explorer', description: 'You are particularly familiar with one type of natural environment and are adept at traveling and surviving in such regions. When you make an Intelligence or Wisdom check related to your favored terrain, your proficiency bonus is doubled if you are using a skill you\'re proficient in.', damage_dice: null, damage_type: null, range_size: 'Special', usage_frequency: 'Passive', level_requirement: 1, class_restriction: 'Ranger' },
      { name: 'Primeval Awareness', description: 'You can use your action and expend one ranger spell slot to focus your awareness on the region around you. For 1 minute per level of the spell slot expended, you can sense whether the following types of creatures are present within 1 mile: aberrations, celestials, dragons, elementals, fey, fiends, and undead.', damage_dice: null, damage_type: 'Detection', range_size: '1 mile', usage_frequency: 'Per spell slot', level_requirement: 3, class_restriction: 'Ranger' },
      { name: 'Land\'s Stride', description: 'Moving through nonmagical difficult terrain costs you no extra movement. You can also pass through nonmagical plants without being slowed by them and without taking damage from them if they have thorns, spines, or similar hazards. In addition, you have advantage on saving throws against plants that are magically created or manipulated to impede movement.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 8, class_restriction: 'Ranger' },
      { name: 'Hide in Plain Sight', description: 'You can spend 1 minute creating camouflage for yourself. You must have access to fresh mud, dirt, plants, soot, and other naturally occurring materials with which to create your camouflage. Once camouflaged, you can try to hide by pressing yourself up against a solid surface that is at least as tall and wide as you are. You gain a +10 bonus to Dexterity (Stealth) checks as long as you remain there without moving or taking actions.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'At will', level_requirement: 10, class_restriction: 'Ranger' },
      { name: 'Vanish', description: 'You can use the Hide action as a bonus action on your turn. Also, you can\'t be tracked by nonmagical means, unless you choose to leave a trail.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'At will', level_requirement: 14, class_restriction: 'Ranger' },
      { name: 'Feral Senses', description: 'You gain preternatural senses that help you fight creatures you can\'t see. When you attack a creature you can\'t see, your inability to see it doesn\'t impose disadvantage on your attack rolls. You are also aware of the location of any invisible creature within 30 feet, provided it isn\'t hidden from you and you aren\'t blinded or deafened.', damage_dice: null, damage_type: null, range_size: '30 feet', usage_frequency: 'Passive', level_requirement: 18, class_restriction: 'Ranger' },
      { name: 'Foe Slayer', description: 'You become an unparalleled hunter of your enemies. Once on each of your turns, you can add your Wisdom modifier to the attack roll or the damage roll of an attack you make against one of your favored enemies. You can choose to use this feature before or after the roll, but before any effects of the roll are applied.', damage_dice: 'WIS modifier', damage_type: 'Varies', range_size: 'Special', usage_frequency: 'Once per turn', level_requirement: 20, class_restriction: 'Ranger' },
      
      // Rogue Skills
      { name: 'Expertise', description: 'Choose two of your skill proficiencies, or one of your skill proficiencies and your proficiency with thieves\' tools. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies. At 6th level, you can choose two more proficiencies to gain this benefit.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 1, class_restriction: 'Rogue' },
      { name: 'Sneak Attack', description: 'You know how to strike subtly and exploit a foe\'s distraction. Once per turn, you can deal extra damage to one creature you hit with an attack if you have advantage on the attack roll, or if another enemy of the target is within 5 feet of it. The attack must use a finesse or ranged weapon. The extra damage increases as you gain levels.', damage_dice: '1d6-10d6', damage_type: 'Weapon', range_size: 'Weapon range', usage_frequency: 'Once per turn', level_requirement: 1, class_restriction: 'Rogue' },
      { name: 'Thieves\' Cant', description: 'You have learned thieves\' cant, a secret mix of dialect, jargon, and code that allows you to hide messages in seemingly normal conversation. Only another creature that knows thieves\' cant understands such messages. It takes four times longer to convey such a message than it does to speak the same idea plainly.', damage_dice: null, damage_type: null, range_size: 'Special', usage_frequency: 'Passive', level_requirement: 1, class_restriction: 'Rogue' },
      { name: 'Cunning Action', description: 'Your quick thinking and agility allow you to move and act quickly. You can take a bonus action on each of your turns to take the Dash, Disengage, or Hide action.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'At will', level_requirement: 2, class_restriction: 'Rogue' },
      { name: 'Uncanny Dodge', description: 'When an attacker that you can see hits you with an attack, you can use your reaction to halve the attack\'s damage against you.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Reaction', level_requirement: 5, class_restriction: 'Rogue' },
      { name: 'Evasion (Rogue)', description: 'You can nimbly dodge out of the way of certain area effects. When you are subjected to an effect that allows you to make a Dexterity saving throw to take only half damage, you instead take no damage if you succeed, and only half damage if you fail.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 7, class_restriction: 'Rogue' },
      { name: 'Reliable Talent', description: 'You have refined your chosen skills until they approach perfection. Whenever you make an ability check that lets you add your proficiency bonus, you can treat a d20 roll of 9 or lower as a 10.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 11, class_restriction: 'Rogue' },
      { name: 'Blindsense', description: 'If you are able to hear, you are aware of the location of any hidden or invisible creature within 10 feet of you.', damage_dice: null, damage_type: null, range_size: '10 feet', usage_frequency: 'Passive', level_requirement: 14, class_restriction: 'Rogue' },
      { name: 'Slippery Mind', description: 'You have acquired greater mental strength. You gain proficiency in Wisdom saving throws.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 15, class_restriction: 'Rogue' },
      { name: 'Elusive', description: 'You are so evasive that attackers rarely gain the upper hand against you. No attack roll has advantage against you while you aren\'t incapacitated.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Passive', level_requirement: 18, class_restriction: 'Rogue' },
      { name: 'Stroke of Luck', description: 'You have an uncanny knack for succeeding when you need to. If your attack misses a target within range, you can turn the miss into a hit. Alternatively, if you fail an ability check, you can treat the d20 roll as a 20.', damage_dice: null, damage_type: null, range_size: 'Special', usage_frequency: '1 per short or long rest', level_requirement: 20, class_restriction: 'Rogue' },
      
      // Sorcerer Skills
      { name: 'Font of Magic', description: 'You tap into a deep wellspring of magic within yourself. You have a number of sorcery points equal to your sorcerer level. You can use sorcery points to gain additional spell slots or sacrifice spell slots to gain additional sorcery points as a bonus action.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Sorcerer level per long rest', level_requirement: 2, class_restriction: 'Sorcerer' },
      { name: 'Metamagic', description: 'You gain the ability to twist your spells to suit your needs. You learn two Metamagic options (Careful, Distant, Empowered, Extended, Heightened, Quickened, Subtle, or Twinned Spell). You can use only one Metamagic option on a spell when you cast it, unless otherwise noted.', damage_dice: null, damage_type: null, range_size: 'Special', usage_frequency: 'Per sorcery points', level_requirement: 3, class_restriction: 'Sorcerer' },
      { name: 'Sorcerous Restoration', description: 'You regain 4 expended sorcery points whenever you finish a short rest.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: 'Per short rest', level_requirement: 20, class_restriction: 'Sorcerer' },
      
      // Warlock Skills
      { name: 'Eldritch Invocations', description: 'Choose from eldritch invocations to customize your warlock. Popular options include: Agonizing Blast (add CHA to Eldritch Blast damage), Armor of Shadows (cast mage armor at will), Devil\'s Sight (see in magical darkness 120ft), Mask of Many Faces (disguise self at will), Misty Visions (silent image at will), Repelling Blast (push targets 10ft with Eldritch Blast), Thirsting Blade (extra attack with pact weapon), Eldritch Sight (detect magic at will), Book of Ancient Secrets (ritual casting), Voice of the Chain Master (communicate through familiar), Lifedrinker (extra necrotic damage with pact weapon). Some require prerequisites like pact boons or warlock levels.', damage_dice: 'Varies', damage_type: 'Varies', range_size: 'Varies', usage_frequency: 'Varies', level_requirement: 2, class_restriction: 'Warlock' },
      { name: 'Eldritch Blast', description: 'A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack. On a hit, the target takes 1d10 force damage. The spell creates more than one beam when you reach higher levels: two beams at 5th level, three beams at 11th level, and four beams at 17th level.', damage_dice: '1d10-4d10', damage_type: 'Force', range_size: '120 feet', usage_frequency: 'At will (cantrip)', level_requirement: 1, class_restriction: 'Warlock' },
      { name: 'Mystic Arcanum', description: 'At 11th level, your patron bestows upon you a magical secret called an arcanum. Choose one 6th-level spell from the warlock spell list as this arcanum. You can cast this spell once without expending a spell slot. You gain additional arcanums at higher levels (7th at 13th, 8th at 15th, 9th at 17th).', damage_dice: 'Varies', damage_type: 'Varies', range_size: 'Varies', usage_frequency: '1 per long rest each', level_requirement: 11, class_restriction: 'Warlock' },
      { name: 'Eldritch Master', description: 'You can draw on your inner reserve of mystical power. You can spend 1 minute entreating your patron for aid to regain all expended spell slots from your Pact Magic feature.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: '1 per long rest', level_requirement: 20, class_restriction: 'Warlock' },
      
      // Wizard Skills
      { name: 'Arcane Recovery', description: 'You have learned to regain some of your magical energy by studying your spellbook. Once per day when you finish a short rest, you can recover expended spell slots. The spell slots can have a combined level equal to or less than half your wizard level (rounded up), and none can be 6th level or higher.', damage_dice: null, damage_type: null, range_size: 'Self', usage_frequency: '1 per day', level_requirement: 1, class_restriction: 'Wizard' },
      { name: 'Spell Mastery', description: 'You have achieved such mastery over certain spells that you can cast them at will. Choose a 1st-level wizard spell and a 2nd-level wizard spell in your spellbook. You can cast those spells at their lowest level without expending a spell slot. If you want to cast either spell at a higher level, you must expend a spell slot as normal.', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: 'At will', level_requirement: 18, class_restriction: 'Wizard' },
      { name: 'Signature Spells', description: 'You gain mastery over two powerful spells and can cast them with little effort. Choose two 3rd-level wizard spells in your spellbook as your signature spells. You always have these spells prepared and can cast each once at 3rd level without expending a spell slot. Once you cast either spell this way, you can\'t do so again until you finish a short or long rest.', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: '1 each per short rest', level_requirement: 20, class_restriction: 'Wizard' },
      
      // Shared Features Across Multiple Classes
      { name: 'Spellcasting', description: 'You have the ability to cast spells from your class spell list. You prepare and cast spells using your spellcasting ability (Intelligence for Wizards, Wisdom for Clerics/Druids/Rangers, Charisma for Bards/Sorcerers/Paladins/Warlocks). Consult your class for details on spell slots, known/prepared spells, and spellcasting focus.', damage_dice: 'Varies', damage_type: 'Varies', range_size: 'Varies', usage_frequency: 'Per spell slots', level_requirement: 1, class_restriction: 'Multiple' },
      { name: 'Pact Magic', description: 'Your arcane research and the magic bestowed on you by your patron have given you facility with spells. You regain all expended spell slots when you finish a short or long rest, but have fewer slots than other full casters. Your spell slots are always cast at the highest level you can cast.', damage_dice: 'Varies', damage_type: 'Varies', range_size: 'Varies', usage_frequency: 'Per short rest', level_requirement: 1, class_restriction: 'Warlock' },
      
      // Subclass Choices and Selection-Based Features
      { name: 'Otherworldly Patron', description: 'Choose your patron: The Archfey (charm and enchantment magic), The Fiend (destructive fire and necrotic powers), The Great Old One (mind-bending psychic abilities). Your choice grants you features at 1st, 6th, 10th, and 14th level.', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: 'Passive', level_requirement: 1, class_restriction: 'Warlock' },
      { name: 'Pact Boon', description: 'Your patron grants you a special boon. Choose one: Pact of the Chain (gain a powerful familiar), Pact of the Blade (summon a magical melee weapon), or Pact of the Tome (gain a grimoire with extra cantrips and rituals).', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: 'Passive', level_requirement: 3, class_restriction: 'Warlock' },
      { name: 'Martial Archetype', description: 'Choose your combat specialization: Champion (improved critical hits), Battle Master (combat maneuvers), Eldritch Knight (fighter/wizard hybrid), or others. Your choice grants features at 3rd, 7th, 10th, 15th, and 18th level.', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: 'Passive', level_requirement: 3, class_restriction: 'Fighter' },
      { name: 'Arcane Tradition', description: 'Choose your school of magic: Abjuration (protective wards), Conjuration (summoning), Divination (foresight), Enchantment (mind control), Evocation (raw damage), Illusion (deception), Necromancy (undead), or Transmutation (transformation). Grants features at 2nd, 6th, 10th, and 14th level.', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: 'Passive', level_requirement: 2, class_restriction: 'Wizard' },
      { name: 'Bard College', description: 'Choose your bardic tradition: College of Lore (knowledge and versatile magic), College of Valor (martial prowess), or others. Your choice grants features at 3rd, 6th, and 14th level.', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: 'Passive', level_requirement: 3, class_restriction: 'Bard' },
      { name: 'Divine Domain', description: 'Choose your deity\'s domain: Knowledge, Life, Light, Nature, Tempest, Trickery, War, or others. Each domain grants bonus spells and features at 1st, 2nd, 6th, 8th, and 17th level.', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: 'Passive', level_requirement: 1, class_restriction: 'Cleric' },
      { name: 'Druid Circle', description: 'Choose your circle: Circle of the Land (terrain-based magic and spell recovery), Circle of the Moon (enhanced Wild Shape combat forms), or others. Grants features at 2nd, 6th, 10th, and 14th level.', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: 'Passive', level_requirement: 2, class_restriction: 'Druid' },
      { name: 'Monastic Tradition', description: 'Choose your monastery\'s tradition: Way of the Open Hand (enhanced unarmed combat), Way of Shadow (stealth and darkness), Way of the Four Elements (elemental spells), or others. Grants features at 3rd, 6th, 11th, and 17th level.', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: 'Passive', level_requirement: 3, class_restriction: 'Monk' },
      { name: 'Sacred Oath', description: 'Choose your oath: Oath of Devotion (classic holy knight), Oath of the Ancients (nature protector), Oath of Vengeance (relentless pursuer), or others. Your oath grants spells and features at 3rd, 7th, 15th, and 20th level.', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: 'Passive', level_requirement: 3, class_restriction: 'Paladin' },
      { name: 'Ranger Archetype', description: 'Choose your ranger path: Hunter (versatile combat options), Beast Master (animal companion), or others. Your choice grants features at 3rd, 7th, 11th, and 15th level.', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: 'Passive', level_requirement: 3, class_restriction: 'Ranger' },
      { name: 'Roguish Archetype', description: 'Choose your archetype: Thief (second-story work and fast hands), Assassin (deadly ambush specialist), Arcane Trickster (rogue/wizard hybrid), or others. Grants features at 3rd, 9th, 13th, and 17th level.', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: 'Passive', level_requirement: 3, class_restriction: 'Rogue' },
      { name: 'Sorcerous Origin', description: 'Choose your magic source: Draconic Bloodline (dragon ancestry and elemental affinity), Wild Magic (chaotic unpredictable effects), or others. Your origin grants features at 1st, 6th, 14th, and 18th level.', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: 'Passive', level_requirement: 1, class_restriction: 'Sorcerer' },
      { name: 'Primal Path', description: 'Choose your barbarian path: Path of the Berserker (frenzied rage), Path of the Totem Warrior (animal spirit powers), or others. Your path grants features at 3rd, 6th, 10th, and 14th level.', damage_dice: null, damage_type: null, range_size: 'Varies', usage_frequency: 'Passive', level_requirement: 3, class_restriction: 'Barbarian' }
    ];

    // Check if skills already exist
    const existingSkillsResult = await pool.query('SELECT name FROM skills');
    const existingSkillNames = new Set(existingSkillsResult.rows.map(row => row.name));
    
    if (existingSkillNames.size > 0) {
      console.log(`Found ${existingSkillNames.size} existing skills, checking for new skills to add...`);
      
      // Update Eldritch Invocations description
      await pool.query(
        `UPDATE skills 
         SET description = $1 
         WHERE name = 'Eldritch Invocations'`,
        ['Choose from eldritch invocations to customize your warlock. Popular options include: Agonizing Blast (add CHA to Eldritch Blast damage), Armor of Shadows (cast mage armor at will), Devil\'s Sight (see in magical darkness 120ft), Mask of Many Faces (disguise self at will), Misty Visions (silent image at will), Repelling Blast (push targets 10ft with Eldritch Blast), Thirsting Blade (extra attack with pact weapon), Eldritch Sight (detect magic at will), Book of Ancient Secrets (ritual casting), Voice of the Chain Master (communicate through familiar), Lifedrinker (extra necrotic damage with pact weapon). Some require prerequisites like pact boons or warlock levels.']
      );
      
      // Insert new skills that don't exist yet
      let newSkillsAdded = 0;
      for (const skill of defaultSkills) {
        if (!existingSkillNames.has(skill.name)) {
          await pool.query(
            `INSERT INTO skills (name, description, damage_dice, damage_type, range_size, usage_frequency, level_requirement, class_restriction)
             VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
            [skill.name, skill.description, skill.damage_dice, skill.damage_type, skill.range_size, skill.usage_frequency, skill.level_requirement, skill.class_restriction]
          );
          newSkillsAdded++;
        }
      }
      
      console.log(`Updated Eldritch Invocations and added ${newSkillsAdded} new skills`);
      return;
    }

    console.log('Seeding default class skills...');

    // Insert all skills
    for (const skill of defaultSkills) {
      await pool.query(
        `INSERT INTO skills (name, description, damage_dice, damage_type, range_size, usage_frequency, level_requirement, class_restriction)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
        [skill.name, skill.description, skill.damage_dice, skill.damage_type, skill.range_size, skill.usage_frequency, skill.level_requirement, skill.class_restriction]
      );
    }

    console.log(`Seeded ${defaultSkills.length} default skills successfully`);
  } catch (error) {
    console.error('Error in skills migration:', error);
    throw error;
  }
};

module.exports = createSkillsTable;
