const { pool } = require('../models/database');

// Default monster templates (campaign_id = NULL = global, available in every campaign)
// Images go in: frontend/public/images/monsters/<filename>
const DEFAULT_MONSTERS = [
  // ─── Common Low-Level Foes ────────────────────────────────────────────────
  {
    name: 'Goblin',
    description: 'Small, green-skinned humanoids that lurk in dark places. Goblins are cowardly but dangerous in numbers, using hit-and-run tactics and dirty tricks to overwhelm their enemies.',
    image_url: '/images/monsters/goblin.png',
    cr: 0.25,
    abilities: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    limb_health: { head: 5, chest: 10, left_arm: 4, right_arm: 4, left_leg: 5, right_leg: 5 },
    limb_ac: { head: 13, chest: 15, left_arm: 12, right_arm: 12, left_leg: 12, right_leg: 12 },
  },
  {
    name: 'Kobold',
    description: 'Tiny reptilian humanoids with a pack mentality and a talent for traps. Kobolds worship dragons and eagerly serve as scouts, trapmakers, and frontline fodder.',
    image_url: '/images/monsters/kobold.png',
    cr: 0.125,
    abilities: { str: 7, dex: 15, con: 9, int: 8, wis: 7, cha: 8 },
    limb_health: { head: 4, chest: 8, left_arm: 3, right_arm: 3, left_leg: 4, right_leg: 4 },
    limb_ac: { head: 12, chest: 12, left_arm: 11, right_arm: 11, left_leg: 11, right_leg: 11 },
  },
  {
    name: 'Skeleton',
    description: 'Reanimated bones of the long dead, driven by necromantic will. Skeletons follow simple commands, are immune to poison and exhaustion, and can be shattered by bludgeoning damage.',
    image_url: '/images/monsters/skeleton.png',
    cr: 0.25,
    abilities: { str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5 },
    limb_health: { head: 6, chest: 13, left_arm: 5, right_arm: 5, left_leg: 7, right_leg: 7 },
    limb_ac: { head: 13, chest: 13, left_arm: 12, right_arm: 12, left_leg: 12, right_leg: 12 },
  },
  {
    name: 'Zombie',
    description: 'Rotting corpses animated by dark magic, groaning and lurching toward warm flesh. Zombies are slow but relentless, and their Undead Fortitude can keep them shambling even after a lethal blow.',
    image_url: '/images/monsters/zombie.png',
    cr: 0.25,
    abilities: { str: 13, dex: 6, con: 16, int: 3, wis: 6, cha: 5 },
    limb_health: { head: 7, chest: 22, left_arm: 7, right_arm: 7, left_leg: 10, right_leg: 10 },
    limb_ac: { head: 8, chest: 8, left_arm: 7, right_arm: 7, left_leg: 7, right_leg: 7 },
  },
  {
    name: 'Orc',
    description: 'Savage humanoids with grey-green skin and protruding tusks. Orcs live for battle and serve brutal warlords. Their Aggressive trait lets them surge forward at the start of combat.',
    image_url: '/images/monsters/orc.png',
    cr: 0.5,
    abilities: { str: 16, dex: 12, con: 16, int: 7, wis: 11, cha: 10 },
    limb_health: { head: 10, chest: 28, left_arm: 10, right_arm: 10, left_leg: 14, right_leg: 14 },
    limb_ac: { head: 11, chest: 13, left_arm: 11, right_arm: 11, left_leg: 11, right_leg: 11 },
  },
  {
    name: 'Gnoll',
    description: 'Hyena-headed demons of the savanna who spread chaos and hunger wherever they roam. Gnolls move like a plague, leaving only bones behind, and are empowered by Yeenoghu\'s demonic hunger.',
    image_url: '/images/monsters/gnoll.png',
    cr: 0.5,
    abilities: { str: 14, dex: 12, con: 11, int: 6, wis: 10, cha: 7 },
    limb_health: { head: 8, chest: 22, left_arm: 8, right_arm: 8, left_leg: 11, right_leg: 11 },
    limb_ac: { head: 12, chest: 15, left_arm: 12, right_arm: 12, left_leg: 12, right_leg: 12 },
  },
  {
    name: 'Hobgoblin',
    description: 'Larger and more disciplined than common goblins, hobgoblins are martial warriors who organize warbands with military precision. Their Martial Advantage allows them to deal bonus damage when allies are adjacent.',
    image_url: '/images/monsters/hobgoblin.png',
    cr: 0.5,
    abilities: { str: 13, dex: 12, con: 12, int: 10, wis: 10, cha: 9 },
    limb_health: { head: 9, chest: 27, left_arm: 9, right_arm: 9, left_leg: 13, right_leg: 13 },
    limb_ac: { head: 16, chest: 18, left_arm: 15, right_arm: 15, left_leg: 14, right_leg: 14 },
  },
  {
    name: 'Giant Rat',
    description: 'Massive rodents the size of dogs, found in sewers, dungeons, and plagued towns. Giant rats bite with filthy teeth and can carry disease. They often swarm prey in packs.',
    image_url: '/images/monsters/giant_rat.png',
    cr: 0.125,
    abilities: { str: 7, dex: 15, con: 11, int: 2, wis: 10, cha: 4 },
    limb_health: { head: 3, chest: 7, left_arm: 2, right_arm: 2, left_leg: 3, right_leg: 3 },
    limb_ac: { head: 11, chest: 12, left_arm: 11, right_arm: 11, left_leg: 11, right_leg: 11 },
  },
  {
    name: 'Stirge',
    description: 'Bloodsucking creatures resembling a cross between a bat and a mosquito. Stirges latch onto a host and drain blood rapidly. They are weak individually but terrifying in swarms.',
    image_url: '/images/monsters/stirge.png',
    cr: 0.125,
    abilities: { str: 4, dex: 16, con: 11, int: 2, wis: 8, cha: 6 },
    limb_health: { head: 3, chest: 5, left_arm: 1, right_arm: 1, left_leg: 2, right_leg: 2 },
    limb_ac: { head: 13, chest: 14, left_arm: 12, right_arm: 12, left_leg: 12, right_leg: 12 },
  },
  {
    name: 'Bandit',
    description: 'Desperate outlaws and cutthroats who prey on travellers. Bandits operate in gangs and while individually unremarkable, they use numbers and ambush tactics to overwhelm their victims.',
    image_url: '/images/monsters/bandit.png',
    cr: 0.125,
    abilities: { str: 11, dex: 12, con: 12, int: 10, wis: 10, cha: 10 },
    limb_health: { head: 7, chest: 18, left_arm: 7, right_arm: 7, left_leg: 9, right_leg: 9 },
    limb_ac: { head: 11, chest: 12, left_arm: 11, right_arm: 11, left_leg: 11, right_leg: 11 },
  },

  // ─── Classic Dungeon Denizens ─────────────────────────────────────────────
  {
    name: 'Mimic',
    description: 'Shape-shifting predators that disguise themselves as mundane objects — most commonly treasure chests. A mimic strikes with a pseudopod and adhesive surface when prey touches it.',
    image_url: '/images/monsters/mimic.png',
    cr: 2,
    abilities: { str: 17, dex: 12, con: 15, int: 5, wis: 13, cha: 8 },
    limb_health: { head: 20, chest: 58, left_arm: 18, right_arm: 18, left_leg: 22, right_leg: 22 },
    limb_ac: { head: 12, chest: 12, left_arm: 11, right_arm: 11, left_leg: 11, right_leg: 11 },
  },
  {
    name: 'Gelatinous Cube',
    description: 'A transparent, 10-foot cube of acidic ooze that slowly moves through dungeon corridors, dissolving everything it engulfs. Nearly invisible until it\'s too late.',
    image_url: '/images/monsters/gelatinous_cube.png',
    cr: 2,
    abilities: { str: 14, dex: 3, con: 20, int: 1, wis: 6, cha: 1 },
    limb_health: { head: 50, chest: 50, left_arm: 50, right_arm: 50, left_leg: 50, right_leg: 50 },
    limb_ac: { head: 6, chest: 6, left_arm: 6, right_arm: 6, left_leg: 6, right_leg: 6 },
  },
  {
    name: 'Owlbear',
    description: 'The terrifying fusion of a bear\'s body and an owl\'s head. Owlbears are aggressive predators that attack on sight and fight to the death. Their screech can be heard miles away.',
    image_url: '/images/monsters/owlbear.png',
    cr: 3,
    abilities: { str: 20, dex: 12, con: 17, int: 3, wis: 12, cha: 7 },
    limb_health: { head: 22, chest: 68, left_arm: 22, right_arm: 22, left_leg: 28, right_leg: 28 },
    limb_ac: { head: 13, chest: 13, left_arm: 12, right_arm: 12, left_leg: 12, right_leg: 12 },
  },
  {
    name: 'Displacer Beast',
    description: 'A panther-like creature with six tentacled legs and the magical ability to project a displaced image of itself, making it appear to be where it is not. Favoured by the Unseelie Court.',
    image_url: '/images/monsters/displacer_beast.png',
    cr: 3,
    abilities: { str: 18, dex: 15, con: 16, int: 6, wis: 12, cha: 8 },
    limb_health: { head: 18, chest: 55, left_arm: 15, right_arm: 15, left_leg: 22, right_leg: 22 },
    limb_ac: { head: 13, chest: 13, left_arm: 12, right_arm: 12, left_leg: 12, right_leg: 12 },
  },
  {
    name: 'Rust Monster',
    description: 'An insectoid scavenger with an antenna that corrodes metal on contact, turning even fine weapons and armour to worthless powder. The bane of well-equipped adventurers.',
    image_url: '/images/monsters/rust_monster.png',
    cr: 0.5,
    abilities: { str: 13, dex: 12, con: 13, int: 2, wis: 13, cha: 6 },
    limb_health: { head: 14, chest: 27, left_arm: 10, right_arm: 10, left_leg: 13, right_leg: 13 },
    limb_ac: { head: 14, chest: 14, left_arm: 13, right_arm: 13, left_leg: 13, right_leg: 13 },
  },
  {
    name: 'Carrion Crawler',
    description: 'A large centipede-like creature with tentacles dripping paralytic poison. Carrion crawlers haunt dark tunnels, feeding on corpses — and anyone they can paralyse and add to their larder.',
    image_url: '/images/monsters/carrion_crawler.png',
    cr: 2,
    abilities: { str: 14, dex: 13, con: 16, int: 1, wis: 12, cha: 5 },
    limb_health: { head: 16, chest: 38, left_arm: 12, right_arm: 12, left_leg: 15, right_leg: 15 },
    limb_ac: { head: 13, chest: 13, left_arm: 12, right_arm: 12, left_leg: 12, right_leg: 12 },
  },
  {
    name: 'Bugbear',
    description: 'Large, stealthy goblinoids that ambush prey in the dark. Bugbears are stronger and meaner than their goblin cousins, relishing cruelty. Their Surprise Attack deals massive bonus damage.',
    image_url: '/images/monsters/bugbear.png',
    cr: 1,
    abilities: { str: 15, dex: 14, con: 13, int: 8, wis: 11, cha: 9 },
    limb_health: { head: 14, chest: 35, left_arm: 12, right_arm: 12, left_leg: 16, right_leg: 16 },
    limb_ac: { head: 14, chest: 16, left_arm: 14, right_arm: 14, left_leg: 13, right_leg: 13 },
  },
  {
    name: 'Gargoyle',
    description: 'Stone demons that perch motionless on ledges and rooftops, indistinguishable from ornamental statues until they strike. They are immune to non-magical physical damage and love ambush attacks.',
    image_url: '/images/monsters/gargoyle.png',
    cr: 2,
    abilities: { str: 15, dex: 11, con: 16, int: 6, wis: 11, cha: 7 },
    limb_health: { head: 18, chest: 52, left_arm: 16, right_arm: 16, left_leg: 20, right_leg: 20 },
    limb_ac: { head: 15, chest: 15, left_arm: 14, right_arm: 14, left_leg: 14, right_leg: 14 },
  },
  {
    name: 'Basilisk',
    description: 'An eight-legged reptile whose gaze turns flesh to stone. Even glimpsing a basilisk\'s reflection can be dangerous. Its petrifying gaze makes this a creature to fear and respect.',
    image_url: '/images/monsters/basilisk.png',
    cr: 3,
    abilities: { str: 16, dex: 8, con: 15, int: 2, wis: 8, cha: 7 },
    limb_health: { head: 20, chest: 52, left_arm: 15, right_arm: 15, left_leg: 20, right_leg: 20 },
    limb_ac: { head: 15, chest: 15, left_arm: 14, right_arm: 14, left_leg: 14, right_leg: 14 },
  },
  {
    name: 'Ogre',
    description: 'Massive, dim-witted brutes that eat everything they can catch. Ogres wield crude clubs and rely on sheer strength and size to crush opposition. They are sometimes enslaved by more powerful creatures.',
    image_url: '/images/monsters/ogre.png',
    cr: 2,
    abilities: { str: 19, dex: 8, con: 16, int: 5, wis: 7, cha: 7 },
    limb_health: { head: 26, chest: 78, left_arm: 26, right_arm: 26, left_leg: 34, right_leg: 34 },
    limb_ac: { head: 11, chest: 11, left_arm: 10, right_arm: 10, left_leg: 10, right_leg: 10 },
  },

  // ─── Iconic Mid-to-High Level Threats ─────────────────────────────────────
  {
    name: 'Beholder',
    description: 'A humanoid creature covered in eye stalks that each fires a different deadly ray — from petrification to disintegration. The central eye emits an antimagic cone. Among the most feared dungeon lords.',
    image_url: '/images/monsters/beholder.png',
    cr: 13,
    abilities: { str: 10, dex: 14, con: 18, int: 17, wis: 15, cha: 17 },
    limb_health: { head: 180, chest: 180, left_arm: 60, right_arm: 60, left_leg: 60, right_leg: 60 },
    limb_ac: { head: 18, chest: 18, left_arm: 17, right_arm: 17, left_leg: 17, right_leg: 17 },
  },
  {
    name: 'Mind Flayer',
    description: 'Aberrant humanoids with octopus-like heads that feed on the brains of sentient creatures. Mind flayers possess psionic powers to stun, dominate, and ultimately devour the minds of their prey.',
    image_url: '/images/monsters/mind_flayer.png',
    cr: 7,
    abilities: { str: 11, dex: 12, con: 12, int: 19, wis: 17, cha: 17 },
    limb_health: { head: 50, chest: 71, left_arm: 28, right_arm: 28, left_leg: 35, right_leg: 35 },
    limb_ac: { head: 15, chest: 15, left_arm: 14, right_arm: 14, left_leg: 14, right_leg: 14 },
  },
  {
    name: 'Lich',
    description: 'A powerful undead wizard who has performed dark rituals to achieve immortality, binding their soul to a phylactery. Liches command armies of undead and possess the full spellcasting abilities of a high-level wizard.',
    image_url: '/images/monsters/lich.png',
    cr: 21,
    abilities: { str: 11, dex: 16, con: 16, int: 20, wis: 14, cha: 16 },
    limb_health: { head: 60, chest: 135, left_arm: 45, right_arm: 45, left_leg: 60, right_leg: 60 },
    limb_ac: { head: 17, chest: 17, left_arm: 16, right_arm: 16, left_leg: 16, right_leg: 16 },
  },
  {
    name: 'Dragon',
    description: 'The most iconic of fantasy monsters. Dragons come in many colours — chromatic (black, blue, green, red, white) are evil, metallic (brass, bronze, copper, gold, silver) are good. Each has a devastating breath weapon and fearsome physical power.',
    image_url: '/images/monsters/dragon.png',
    cr: 17,
    abilities: { str: 27, dex: 10, con: 25, int: 16, wis: 13, cha: 21 },
    limb_health: { head: 80, chest: 256, left_arm: 80, right_arm: 80, left_leg: 100, right_leg: 100 },
    limb_ac: { head: 19, chest: 19, left_arm: 18, right_arm: 18, left_leg: 18, right_leg: 18 },
  },
  {
    name: 'Troll',
    description: 'Enormous, loping giants with rubbery green hide and an almost supernatural regeneration. Trolls regrow wounds between turns, making fire and acid the only reliable way to finish them off.',
    image_url: '/images/monsters/troll.png',
    cr: 5,
    abilities: { str: 18, dex: 13, con: 20, int: 7, wis: 9, cha: 7 },
    limb_health: { head: 40, chest: 84, left_arm: 35, right_arm: 35, left_leg: 42, right_leg: 42 },
    limb_ac: { head: 15, chest: 15, left_arm: 14, right_arm: 14, left_leg: 14, right_leg: 14 },
  },
  {
    name: 'Aboleth',
    description: 'Ancient aquatic aberrations with vast psychic powers and a perfect racial memory stretching back to before the gods. Aboleths enslave creatures with their mucus and feed on memories.',
    image_url: '/images/monsters/aboleth.png',
    cr: 10,
    abilities: { str: 21, dex: 9, con: 15, int: 18, wis: 15, cha: 18 },
    limb_health: { head: 60, chest: 135, left_arm: 45, right_arm: 45, left_leg: 55, right_leg: 55 },
    limb_ac: { head: 17, chest: 17, left_arm: 16, right_arm: 16, left_leg: 16, right_leg: 16 },
  },
  {
    name: 'Vampire',
    description: 'Immortal undead lords of the night who sustain themselves on blood. Vampires possess superhuman strength and charm, can transform into bats or mist, and regenerate damage — unless reduced to 0 HP in sunlight or by a stake through the heart.',
    image_url: '/images/monsters/vampire.png',
    cr: 13,
    abilities: { str: 18, dex: 18, con: 18, int: 17, wis: 15, cha: 18 },
    limb_health: { head: 70, chest: 144, left_arm: 55, right_arm: 55, left_leg: 66, right_leg: 66 },
    limb_ac: { head: 16, chest: 16, left_arm: 15, right_arm: 15, left_leg: 15, right_leg: 15 },
  },
  {
    name: 'Hag',
    description: 'Wicked, ancient witches who delight in corruption and misery. Hags (Green, Night, Sea, and others) share powerful spellcasting, illusory powers, and terrifying claws. They often form covens to amplify their magic.',
    image_url: '/images/monsters/hag.png',
    cr: 3,
    abilities: { str: 18, dex: 12, con: 16, int: 13, wis: 14, cha: 14 },
    limb_health: { head: 30, chest: 82, left_arm: 28, right_arm: 28, left_leg: 36, right_leg: 36 },
    limb_ac: { head: 17, chest: 17, left_arm: 16, right_arm: 16, left_leg: 16, right_leg: 16 },
  },
  {
    name: 'Wraith',
    description: 'A spirit of undying hatred and malice that exists only to drain the life from the living. Wraiths pass through walls, can only be harmed by magic, and their Life Drain reduces a target\'s hit point maximum.',
    image_url: '/images/monsters/wraith.png',
    cr: 5,
    abilities: { str: 6, dex: 16, con: 16, int: 12, wis: 14, cha: 15 },
    limb_health: { head: 35, chest: 67, left_arm: 20, right_arm: 20, left_leg: 25, right_leg: 25 },
    limb_ac: { head: 13, chest: 13, left_arm: 12, right_arm: 12, left_leg: 12, right_leg: 12 },
  },
  {
    name: 'Hydra',
    description: 'A massive multi-headed serpentine beast that grows two heads for every one chopped off. Each head attacks independently. Fire or cauterising the stump prevents regrowth.',
    image_url: '/images/monsters/hydra.png',
    cr: 8,
    abilities: { str: 20, dex: 12, con: 20, int: 2, wis: 10, cha: 7 },
    limb_health: { head: 110, chest: 172, left_arm: 50, right_arm: 50, left_leg: 60, right_leg: 60 },
    limb_ac: { head: 15, chest: 15, left_arm: 14, right_arm: 14, left_leg: 14, right_leg: 14 },
  },

  // ─── Extraplanar & Legendary Beings ──────────────────────────────────────
  {
    name: 'Balor',
    description: 'Among the most powerful demons, the balor is a towering winged fiend wreathed in flame and crackling lightning. It wields a vorpal sword and a flaming whip, and explodes in a cataclysmic death throes when slain.',
    image_url: '/images/monsters/balor.png',
    cr: 19,
    abilities: { str: 26, dex: 15, con: 22, int: 20, wis: 12, cha: 22 },
    limb_health: { head: 120, chest: 262, left_arm: 90, right_arm: 90, left_leg: 110, right_leg: 110 },
    limb_ac: { head: 19, chest: 19, left_arm: 18, right_arm: 18, left_leg: 18, right_leg: 18 },
  },
  {
    name: 'Dretch',
    description: 'The lowliest of demons, bloated and pathetic, but still reeking of the Abyss. Dretches are often summoned as expendable cannon fodder. Their stench cloud nauseates nearby creatures.',
    image_url: '/images/monsters/dretch.png',
    cr: 0.25,
    abilities: { str: 11, dex: 11, con: 12, int: 5, wis: 8, cha: 3 },
    limb_health: { head: 6, chest: 18, left_arm: 6, right_arm: 6, left_leg: 8, right_leg: 8 },
    limb_ac: { head: 11, chest: 11, left_arm: 10, right_arm: 10, left_leg: 10, right_leg: 10 },
  },
  {
    name: 'Pit Fiend',
    description: 'The supreme commanders of the Nine Hells, pit fiends are massive, winged devils of terrifying power. They command legions of lesser devils and can use wish once per day, alongside a vast array of infernal magic.',
    image_url: '/images/monsters/pit_fiend.png',
    cr: 20,
    abilities: { str: 26, dex: 14, con: 24, int: 22, wis: 18, cha: 24 },
    limb_health: { head: 110, chest: 300, left_arm: 100, right_arm: 100, left_leg: 120, right_leg: 120 },
    limb_ac: { head: 19, chest: 19, left_arm: 18, right_arm: 18, left_leg: 18, right_leg: 18 },
  },
  {
    name: 'Imp',
    description: 'A small, winged devil that serves as a familiar or spy for warlocks and wizards making infernal pacts. Imps can turn invisible, shapeshift into small animals, and sting with a poisonous tail.',
    image_url: '/images/monsters/imp.png',
    cr: 1,
    abilities: { str: 6, dex: 17, con: 13, int: 11, wis: 12, cha: 14 },
    limb_health: { head: 8, chest: 10, left_arm: 3, right_arm: 3, left_leg: 5, right_leg: 5 },
    limb_ac: { head: 13, chest: 13, left_arm: 12, right_arm: 12, left_leg: 12, right_leg: 12 },
  },
  {
    name: 'Flesh Golem',
    description: 'A shambling horror stitched together from the body parts of multiple corpses and animated by lightning. Flesh golems are immune to poison and many spells, but can be driven berserk by certain magic.',
    image_url: '/images/monsters/flesh_golem.png',
    cr: 5,
    abilities: { str: 19, dex: 9, con: 18, int: 6, wis: 10, cha: 5 },
    limb_health: { head: 44, chest: 93, left_arm: 35, right_arm: 35, left_leg: 44, right_leg: 44 },
    limb_ac: { head: 9, chest: 9, left_arm: 8, right_arm: 8, left_leg: 8, right_leg: 8 },
  },
  {
    name: 'Stone Golem',
    description: 'A massive humanoid carved from solid stone and imbued with animating magic. Stone golems are nearly impervious to magical effects and can slow creatures with a magical aura, making them excellent dungeon guardians.',
    image_url: '/images/monsters/stone_golem.png',
    cr: 10,
    abilities: { str: 22, dex: 9, con: 20, int: 3, wis: 11, cha: 1 },
    limb_health: { head: 60, chest: 178, left_arm: 60, right_arm: 60, left_leg: 80, right_leg: 80 },
    limb_ac: { head: 17, chest: 17, left_arm: 16, right_arm: 16, left_leg: 16, right_leg: 16 },
  },
  {
    name: 'Iron Golem',
    description: 'The pinnacle of golem construction: a hulking, indestructible figure of forged iron. Iron golems breathe a cloud of poisonous gas and can only be harmed by adamantine or magical weapons of +3 or better.',
    image_url: '/images/monsters/iron_golem.png',
    cr: 16,
    abilities: { str: 24, dex: 9, con: 20, int: 3, wis: 11, cha: 1 },
    limb_health: { head: 80, chest: 210, left_arm: 70, right_arm: 70, left_leg: 90, right_leg: 90 },
    limb_ac: { head: 20, chest: 20, left_arm: 19, right_arm: 19, left_leg: 19, right_leg: 19 },
  },
  {
    name: 'Air Elemental',
    description: 'A swirling vortex of wind and thunder given sentient form. Air elementals move with incredible speed and can envelop creatures in their whirlwind. They are immune to poison and resist non-magical damage.',
    image_url: '/images/monsters/air_elemental.png',
    cr: 5,
    abilities: { str: 14, dex: 20, con: 14, int: 6, wis: 10, cha: 6 },
    limb_health: { head: 45, chest: 90, left_arm: 30, right_arm: 30, left_leg: 40, right_leg: 40 },
    limb_ac: { head: 15, chest: 15, left_arm: 14, right_arm: 14, left_leg: 14, right_leg: 14 },
  },
  {
    name: 'Earth Elemental',
    description: 'A massive creature of stone and soil, slow but tremendously powerful. Earth elementals can move through solid ground and stone as easily as humans walk, emerging to ambush foes.',
    image_url: '/images/monsters/earth_elemental.png',
    cr: 5,
    abilities: { str: 20, dex: 8, con: 20, int: 5, wis: 10, cha: 5 },
    limb_health: { head: 50, chest: 126, left_arm: 45, right_arm: 45, left_leg: 55, right_leg: 55 },
    limb_ac: { head: 17, chest: 17, left_arm: 16, right_arm: 16, left_leg: 16, right_leg: 16 },
  },
  {
    name: 'Fire Elemental',
    description: 'A roaring column of living flame. Fire elementals ignite everything they touch and are immune to fire damage, though water is their bane. Their mere touch burns, and proximity to their blazing form is dangerous.',
    image_url: '/images/monsters/fire_elemental.png',
    cr: 5,
    abilities: { str: 10, dex: 17, con: 16, int: 6, wis: 10, cha: 7 },
    limb_health: { head: 45, chest: 102, left_arm: 35, right_arm: 35, left_leg: 44, right_leg: 44 },
    limb_ac: { head: 13, chest: 13, left_arm: 12, right_arm: 12, left_leg: 12, right_leg: 12 },
  },
  {
    name: 'Water Elemental',
    description: 'A crashing wave and surging current given form. Water elementals can move through narrow spaces as water and engulf creatures to drown them. They are at full power near large bodies of water.',
    image_url: '/images/monsters/water_elemental.png',
    cr: 5,
    abilities: { str: 18, dex: 14, con: 18, int: 5, wis: 10, cha: 8 },
    limb_health: { head: 50, chest: 114, left_arm: 40, right_arm: 40, left_leg: 50, right_leg: 50 },
    limb_ac: { head: 14, chest: 14, left_arm: 13, right_arm: 13, left_leg: 13, right_leg: 13 },
  },
  {
    name: 'Tarrasque',
    description: 'The most destructive creature in existence — a legendary engine of annihilation that periodically awakens to lay waste to civilisation before falling into a comatose slumber. It reflects magic, ignores most damage, and regenerates. Only a wish spell can truly slay it.',
    image_url: '/images/monsters/tarrasque.png',
    cr: 30,
    abilities: { str: 30, dex: 11, con: 30, int: 3, wis: 11, cha: 11 },
    limb_health: { head: 350, chest: 676, left_arm: 250, right_arm: 250, left_leg: 300, right_leg: 300 },
    limb_ac: { head: 25, chest: 25, left_arm: 24, right_arm: 24, left_leg: 24, right_leg: 24 },
  },
];

const seedDefaultMonsters = async () => {
  try {
    // Check if any global monsters already exist (idempotent)
    const existing = await pool.query(
      `SELECT COUNT(*) FROM monsters WHERE campaign_id IS NULL`
    );
    if (parseInt(existing.rows[0].count) > 0) {
      console.log('✓ Default monsters already seeded — skipping');
      return;
    }

    console.log('Seeding default monster templates...');
    for (const monster of DEFAULT_MONSTERS) {
      await pool.query(
        `INSERT INTO monsters
           (campaign_id, name, description, image_url, abilities, limb_health, limb_ac, cr, visible_to_players)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
        [
          null,
          monster.name,
          monster.description,
          monster.image_url,
          JSON.stringify(monster.abilities),
          JSON.stringify(monster.limb_health),
          JSON.stringify(monster.limb_ac),
          monster.cr ?? 0,
          false // hidden by default — DM must reveal
        ]
      );
    }
    console.log(`✅ Seeded ${DEFAULT_MONSTERS.length} default monsters`);
  } catch (error) {
    console.warn('seed_default_monsters:', error.message);
  }
};

module.exports = seedDefaultMonsters;
